### ISSUE TITLE
break_column_before

### ISSUE THREAD

**Issue by davidgohel** [cardiomoon/rrtable#2]
Dear Keon-Woong

I am cleaning officer code and trying to improve internals and API - I just noticed you are importing `break_column_before` but not using it. This function is deprecated since some times now and I can't remove it from officer without causing you troubles on CRAN. 

https://github.com/cardiomoon/rrtable/blob/545a9751c4f44cc799410fd993dc4d7019a32b31/R/add_2ggplots.R#L146

Could you remove that function importation? 

KR
David

**Comment by cardiomoon** [comment]
Dear David,

Thank you for your suggestion.

I will clear both packages and submit to CRAN till this weekend.

Thank you for your wonderful package.

Keon-Woong Moon
